basePath: /
definitions:
  db.User:
    properties:
      age:
        type: integer
      id:
        type: integer
      name:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:3500
info:
  contact:
    email: test@gmail.com
    name: Petar Vico
    url: https://google.com
  description: This is a template backend REST API written in Go with the Fiber framework
    using SQLC.
  title: Template Go (Fiber) Backend API
  version: "1.0"
paths:
  /user/create-default:
    post:
      consumes:
      - application/json
      description: create default users
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: Create default users
      tags:
      - users
  /user/list:
    get:
      consumes:
      - application/json
      description: get users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/db.User'
            type: array
        "500":
          description: Internal Server Error
      security:
      - BearerAuth: []
      summary: List users
      tags:
      - users
securityDefinitions:
  BearerAuth:
    description: Enter the token with the `Bearer ` prefix, e.g., "Bearer abcde12345"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
